[package]
name = "AutoGrader"
description = "AutoGrader Rust-backend"
version = "0.1.0"
authors = ["Thanapat Chotipun <devpatrick.cho@gmail.com>"]
edition = "2021"

[dependencies]
clap = { version = "2.33.3", features =["yaml","color","suggestions"] }
glob = "0.3.0"
log = { version = "0.4.14", features = ["std"] }
rand = "0.8.4"
serde = { version = "^1.0", features = ["derive"] }
tokio = { version = "^1.13.0", features = ["full"] }
toml = "^0.5.8"