[package]
name = "AutoGrader"
description = "AutoGrader Rust-backend"
version = "0.1.0"
authors = ["Thanapat Chotipun <devpatrick.cho@gmail.com>"]
edition = "2021"

[dependencies]
tokio = { version = "1.13.0", features = ["full"] }
toml = "0.5.8"
serde = { version = "1.0", features = ["derive"] }
clap = { version = "2.33.3", features =["yaml","color","suggestions"] }